### ISSUE TITLE
Non-ASCII characters in filenames are incorrectly removed or rearranged

### ISSUE THREAD

**Issue by elsy0111** [yonep3904/pdf-editor#1]
When processing a filename containing non-ASCII characters, parts of the filename are removed or rearranged unexpectedly. For instance, the file name 応用数学II_課題.pdf is transformed into II_.pdf課題.

Create a file with the name 応用数学II_課題.pdf.
Process the file using [**YOUR SYSTEM**](https://pdf-editor-red-seven.vercel.app/).
Check the output filename.

Expected behavior:
The filename should remain unchanged as 応用数学II_課題.pdf.
Actual behavior:
The filename is transformed into II_.pdf課題, where parts of the name are removed or rearranged incorrectly.

Environment:

Windows 10 Pro 22H2
Chrome (131.0.6778.205 (Official Build))
Commit Version : [f0b0042](https://github.com/yonep3904/pdf-editor/commit/f0b004256a39ec3dd9e72155be8ba36fd66bb8f4)

**Comment by yonep3904** [comment]
Thank you for reporting this issue. We have identified and fixed the bug related to how filenames containing non-ASCII characters were processed.

Cause:
The issue was caused by our use of the secure_filename function, which, by default, strips non-ASCII characters to ensure compatibility and security. This behavior inadvertently removed or rearranged parts of filenames containing non-ASCII characters, such as `応用数学II_課題.pdf`.

Fix:
We have updated our system to properly handle non-ASCII characters in filenames while still ensuring compatibility and security. The updated implementation now supports non-ASCII characters without altering the filename unnecessarily.

Steps taken to fix the issue:
1. Modified the filename sanitization logic to allow non-ASCII characters while replacing only unsafe characters.
1. Tested the updated implementation with various filenames, including `応用数学II_課題.pdf`, to confirm that filenames remain unchanged after processing.

Next Steps:
Please update your system to the latest version and try uploading the file again. If you encounter any further issues, don't hesitate to let us know.

We appreciate your patience and detailed report!

**Comment by elsy0111** [comment]
thanks! (for GPT)
